version: '3.9'
services:
  db:
    image: postgres:11.13
    ports:
      - '5432:5432'
    volumes:
      - data-db:/var/lib/postgres/data
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Moscow
volumes:
  data-db:
    driver: local
